version: "3.7"
services:
  app:
    container_name: employee_api
    build: .
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - .:/usr/app
  db:
    container_name: postgres-employees-api
    image: postgres:12.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/lib/db

volumes:
  data: {}
